
services:
  - type: web
    name: trello-smartsheet-2way-sync
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: PUBLIC_BASE_URL
        sync: false
      - key: SMARTSHEET_ACCESS_TOKEN
        sync: false
      - key: SMARTSHEET_SHEET_ID
        sync: false
      - key: SMARTSHEET_WEBHOOK_SHARED_SECRET
        sync: false
      - key: TRELLO_KEY
        sync: false
      - key: TRELLO_TOKEN
        sync: false
      - key: TRELLO_BOARD_ID
        sync: false
      - key: TRELLO_CUSTOM_FIELD_SMARTSHEET_ROW_ID
        sync: false
      - key: ADMIN_SECRET
        sync: false
